[versions]
openapi = "7.5.0"
moshi = "1.15.1"
swagger-codegen = "2.19.2"
maven-publish = "0.29.0"

[libraries]
openapi-generator = { group = "org.openapitools", name = "openapi-generator-cli", version.ref = "openapi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }

[plugins]
swagger-codegen = { id = "org.hidetake.swagger.generator", version.ref = "swagger-codegen" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }