//
// AnnotationMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct AnnotationMetadata: Codable, Hashable {
    public var datasourceNames: [String]?

    public init(datasourceNames: [String]? = nil) {
        self.datasourceNames = datasourceNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case datasourceNames = "datasource_names"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(datasourceNames, forKey: .datasourceNames)
    }
}
