//
// Lane.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct Lane: Codable, Hashable {
    public var indications: [String]?
    public var valid: Bool?

    public init(indications: [String]? = nil, valid: Bool? = nil) {
        self.indications = indications
        self.valid = valid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case indications
        case valid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(indications, forKey: .indications)
        try container.encodeIfPresent(valid, forKey: .valid)
    }
}
