//
// Route.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct Route: Codable, Hashable {
    /** The distance traveled by the route, in double meters. */
    public var distance: Double?
    /** The estimated travel time, in double number of seconds. */
    public var duration: Double?
    public var geometry: AnyCodable?
    public var weight: Double?
    public var weightName: String?
    public var legs: [RouteLeg]?

    public init(distance: Double? = nil, duration: Double? = nil, geometry: AnyCodable? = nil, weight: Double? = nil, weightName: String? = nil, legs: [RouteLeg]? = nil) {
        self.distance = distance
        self.duration = duration
        self.geometry = geometry
        self.weight = weight
        self.weightName = weightName
        self.legs = legs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distance
        case duration
        case geometry
        case weight
        case weightName = "weight_name"
        case legs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(distance, forKey: .distance)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(geometry, forKey: .geometry)
        try container.encodeIfPresent(weight, forKey: .weight)
        try container.encodeIfPresent(weightName, forKey: .weightName)
        try container.encodeIfPresent(legs, forKey: .legs)
    }
}
