//
// ViaWaypoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ViaWaypoint: Codable, Hashable {
    public var distanceFromStart: Double?
    public var geometryIndex: Int?
    public var waypointIndex: Int?

    public init(distanceFromStart: Double? = nil, geometryIndex: Int? = nil, waypointIndex: Int? = nil) {
        self.distanceFromStart = distanceFromStart
        self.geometryIndex = geometryIndex
        self.waypointIndex = waypointIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case distanceFromStart = "distance_from_start"
        case geometryIndex = "geometry_index"
        case waypointIndex = "waypoint_index"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(distanceFromStart, forKey: .distanceFromStart)
        try container.encodeIfPresent(geometryIndex, forKey: .geometryIndex)
        try container.encodeIfPresent(waypointIndex, forKey: .waypointIndex)
    }
}
